# Generated by Django 5.2.8 on 2025-12-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_hospital_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetails',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
