# Generated by Django 5.2.8 on 2025-12-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_doctordetails_is_archived_patientdetails_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='chronic_disease',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
