# Generated by Django 5.2.8 on 2025-12-15 09:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_passwordresetotp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmenttype',
            options={'ordering': ['type_name']},
        ),
        migrations.AlterModelOptions(
            name='doctoravailability',
            options={'ordering': ['doctor', 'day_of_week', 'start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='doctorappointmenttype',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='appointmenttype',
            name='type_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='doctorappointmenttype',
            name='appointment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointment_types', to='accounts.appointmenttype'),
        ),
        migrations.AlterField(
            model_name='doctorappointmenttype',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointment_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctorappointmenttype',
            name='duration_minutes',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='doctorappointmenttype',
            constraint=models.UniqueConstraint(fields=('doctor', 'appointment_type'), name='uniq_doctor_appointment_type'),
        ),
        migrations.AddConstraint(
            model_name='doctoravailability',
            constraint=models.UniqueConstraint(fields=('doctor', 'day_of_week'), name='uniq_doctor_day_of_week'),
        ),
        migrations.AddConstraint(
            model_name='doctoravailability',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='chk_start_time_before_end_time'),
        ),
    ]
