# Generated by Django 5.2.8 on 2025-12-25 14:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_appointmenttype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSpecificVisitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_specific_visit_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['doctor', 'name'],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'name'), name='uniq_doctor_specific_visit_type_name')],
            },
        ),
    ]
