# Generated by Django 5.2.8 on 2025-12-27 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_doctorspecificvisittype'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttype',
            name='default_duration_minutes',
            field=models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='appointmenttype',
            name='requires_approved_files',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20),
        ),
    ]
