# Generated by Django 5.2.8 on 2026-01-21 07:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_triageassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceCancellationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('absence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_logs', to='accounts.doctorabsence')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_cancellation_logs', to='accounts.appointment')),
            ],
            options={
                'ordering': ['-cancelled_at'],
                'constraints': [models.UniqueConstraint(fields=('absence', 'appointment'), name='uniq_absence_appointment_cancel_log')],
            },
        ),
        migrations.CreateModel(
            name='RebookingPriorityToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('absence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rebooking_tokens', to='accounts.doctorabsence')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='rebooking_tokens_issued', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='rebooking_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['patient', 'is_active', 'expires_at'], name='accounts_re_patient_c305fa_idx'), models.Index(fields=['doctor', 'is_active', 'expires_at'], name='accounts_re_doctor__112154_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('issued_at__lt', models.F('expires_at'))), name='chk_token_issued_before_expires')],
            },
        ),
        migrations.CreateModel(
            name='UrgentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms_text', models.TextField(blank=True, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('bp_systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bp_diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('confidence', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('missing_fields', models.JSONField(blank=True, default=list)),
                ('score_version', models.CharField(blank=True, max_length=32, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('handled', 'Handled'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('appointment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urgent_requests', to='accounts.appointmenttype')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='urgent_requests_received', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='urgent_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['doctor', 'status', 'created_at'], name='accounts_ur_doctor__fddded_idx'), models.Index(fields=['patient', 'created_at'], name='accounts_ur_patient_157267_idx'), models.Index(fields=['score', 'created_at'], name='accounts_ur_score_b50d45_idx')],
            },
        ),
    ]
