# Generated by Django 5.2.8 on 2026-01-21 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_absencecancellationlog_rebookingprioritytoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgentrequest',
            name='handled_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urgent_requests_handled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='urgentrequest',
            name='rejected_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
