# Generated by Django 5.2.8 on 2026-01-22 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_urgentrequest_handled_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgentrequest',
            name='handled_type',
            field=models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('rejected', 'Rejected')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='urgentrequest',
            name='scheduled_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_urgent_request', to='accounts.appointment'),
        ),
    ]
