# Generated by Django 5.2.8 on 2026-01-23 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_urgentrequest_handled_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rebookingprioritytoken',
            name='consumed_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_rebooking_tokens', to='accounts.appointment'),
        ),
        migrations.AddField(
            model_name='rebookingprioritytoken',
            name='consumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='rebookingprioritytoken',
            index=models.Index(fields=['patient', 'doctor', 'is_active', 'expires_at'], name='accounts_re_patient_86b56a_idx'),
        ),
        migrations.AddIndex(
            model_name='rebookingprioritytoken',
            index=models.Index(fields=['consumed_appointment'], name='accounts_re_consume_c3847e_idx'),
        ),
        migrations.AddConstraint(
            model_name='rebookingprioritytoken',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('consumed_appointment__isnull', True), ('consumed_at__isnull', True)), ('is_active', False), _connector='OR'), name='chk_consumed_token_is_inactive'),
        ),
    ]
