# Generated by Django 5.2.8 on 2026-01-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_rebookingprioritytoken_consumed_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='activity_level',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='moderate', max_length=10),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='alcohol_use',
            field=models.CharField(choices=[('none', 'None'), ('occasional', 'Occasional'), ('regular', 'Regular')], default='none', max_length=12),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='bp_measured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='cigarettes_per_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='has_asthma_copd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='has_diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='has_heart_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='has_hypertension',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='has_kidney_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='hba1c_measured_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='is_pregnant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='last_bp_diastolic',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='last_bp_systolic',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='last_hba1c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='smoking_status',
            field=models.CharField(choices=[('never', 'Never'), ('former', 'Former'), ('current', 'Current')], default='never', max_length=10),
        ),
    ]
